Differentiate certificates comes from different relations
canonical/certificate-transfer-interface pull request #17
Opened 2023-08-23 10:53 UTC by gatici

# Description

This PR adds relations ids to set_certificate and remove_certificate operations for Certificate Transfer Provider.
It aims to fix https://github.com/canonical/certificate-transfer-interface/issues/6

## Checklist

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that validate the behaviour of the software.
- [x] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have bumped the version of any required library.

2023-08-23 11:23 UTC, simskij commented on lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
> +
If the lack of a relation id will raise an error, we might as well mark it as non-optional in the function signature

2023-08-23 12:02 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
> +            logger.warning("relation_id should be provided.")
Similar to @simskij 's comment. If it should be provided let's not make it optional

2023-08-23 12:13 UTC, DanielArndt requested changes

2023-08-23 12:13 UTC, DanielArndt commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +        relation_id = relation_id + 5
Why 5? This magic number should be documented if we can't easily avoid using it. Either a self-explanatory variable name (preferable) or a comment.

2023-08-23 12:13 UTC, DanielArndt commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +        relation_id = relation_id + 5
We're making an assumption here that the relation doesn't exist already. We should assert that first before relying on it.

2023-08-23 12:27 UTC, gatici commented on tests/unit/charms/certificate_transfer_interface/v0/dummy_requirer_charm/src/charm.py
> +        print(event.relation_id)
We do no need them. Removed.

2023-08-23 12:28 UTC, gatici commented on lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
> +            logger.warning("relation_id should be provided.")
We made relation_id parameter mandatory.

2023-08-23 12:29 UTC, gatici commented on lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
> +
We made relation_id parameter mandatory.

2023-08-23 12:52 UTC, gatici commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +        relation_id = relation_id + 5
We proved that this relation does not exist in the latest commit.

2023-08-23 13:22 UTC, DanielArndt approved these changes
Added some comments that I think would improve readability, but nothing major. Otherwise LGTM.

2023-08-23 13:22 UTC, DanielArndt commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +        wrong_relation_id = (
`invalid_relation_id` or `missing_relation_id` might be more appropriate

2023-08-23 13:22 UTC, DanielArndt commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            relation_id + 2
To be a little pedantic, it's still unclear to me if the number `2` actually matters... could it be `1`?

Can we just re-use the relation id `0` like we do in the other test?

2023-08-23 13:22 UTC, DanielArndt commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            )
It might be worth breaking this out into a `validate_relation_does_not_exist()` function and re-use in the other test as well. 

It may improve readability by telling the person what we're doing here.

To take this a step further, you could create a helper function that gets you an invalid relation id, and abstract this all away from the test.

2023-08-23 13:45 UTC, merged

2023-08-23 14:18 UTC, gatici commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            relation_id + 2
The number is not matter, it can be anything. We are sure that it is not equal to relation_id as we are adding with relation id.
In the further lines, we are validating that this relation does not exist.

2023-08-23 15:33 UTC, gatici commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            )
As we are calling it just 2 times for the moment and it's very simple, I  did not change it. But I am keeping it  in my mind as  an improvement.

2023-08-24 08:54 UTC, gatici commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            relation_id + 2
> To be a little pedantic, it's still unclear to me if the number `2` actually matters... could it be `1`?
> 
> Can we just re-use the relation id `0` like we do in the other test?

The previous test does not have any relation but that one has a relation and relation_id already. So we are adding a random number with the existing relation id which makes us sure that they are different:  relation_id  != relation_id + 2

2023-08-24 09:35 UTC, gatici commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +        wrong_relation_id = (
This is addressed in PR: https://github.com/canonical/certificate-transfer-interface/pull/19

2023-08-24 09:35 UTC, gatici commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            )
This is addressed in PR: https://github.com/canonical/certificate-transfer-interface/pull/19

2023-08-24 11:23 UTC, DanielArndt commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            relation_id + 2
> The number is not matter, it can be anything.

That is sort of what I figured, but to the reader who just sees the number `2`, they are unsure if it has any special meaning. This is referred to as a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)#Unnamed_numerical_constants). It may seem a little pedantic but it's generally a good idea to both name these (i.e. `arbitrary_offset = ...`) and use the simplest value possible (usually `1`).

> The previous test does not have any relation but that one has a relation and relation_id already. So we are adding a random number with the existing relation id which makes us sure that they are different: relation_id != relation_id + 2

I may have misunderstood whether you were trying to get an _invalid_ number, or just a _different_ number, so it's definitely worth making sure that is clear.

2023-08-24 11:31 UTC, gatici commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            relation_id + 2
As we have only one relation according to our test setup, the other relation numbers are invalid and different than the correct one. So invalid relation_id still makes sense.

2023-08-24 11:44 UTC, DanielArndt commented on tests/unit/charms/certificate_transfer_interface/v0/test_certificate_transfer_provides.py
> +            relation_id + 2
Again, to be pedantic (which I love being :laughing: ), it's less important what is true, and more important what the intention is. 

The assumptions (in this case, that there is only one relation) may change in the future. The test should still make sense -- even if the value has to be updated -- the names should make it obvious that the intention hasn't changed.