feat: Use lists for v1 of certificate interface
canonical/certificate-transfer-interface pull request #89
Opened 2024-07-11 11:02 UTC by kayra1

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2024-07-12 10:26 UTC, saltiyazan requested changes
In general looks good.
I provided some comments.
The approach in the tests is new for me.
I will re-request the team's review as the PR is large.

2024-07-12 10:26 UTC, saltiyazan commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    """Charm Event triggered when a TLS certificate is available."""
How about something like?
```suggestion
    """Charm Event triggered when a CA certificates list is updated."""
```

2024-07-12 10:26 UTC, saltiyazan commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    """Charm Event triggered when a TLS certificate is removed."""
```suggestion
    """Charm Event triggered when a CA certificate is removed."""
```

2024-07-12 10:26 UTC, saltiyazan commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    """TLS certificates requirer class to be instantiated by TLS certificates requirers."""
This isn't quite accurate.
This is not an implementation of the TLS Certificates interface.

2024-07-12 10:26 UTC, saltiyazan commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +        """Generates/use private key and observes relation changed event.
No private keys are used.

2024-07-12 10:26 UTC, saltiyazan commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +        """Emit certificate available event.
```suggestion
        """Emits certificate set updated event.
```

2024-07-12 10:26 UTC, saltiyazan commented on tests/unit/charms/certificate_transfer_interface/v1/test_certificate_transfer_provides_v1.py
> +
We don't do this in other places. We would usually look that the `set_relation_data` was not called.
I don't have a strong opinion but I prefer not to look at logs.
I'll leave this for discussion.

2024-07-12 11:32 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +        )
updated

2024-07-12 11:32 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +from lib.charms.certificate_transfer_interface.v0.certificate_transfer import (
updated the lib docs

2024-07-12 11:32 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +from lib.charms.certificate_transfer_interface.v0.certificate_transfer import(
updated the lib docs

2024-07-12 11:32 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +charmcraft fetch-lib charms.certificate_transfer_interface.v0.certificate_transfer
updated the lib docs

2024-07-12 11:34 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +        # TODO: Leader only
added the check

2024-07-12 11:38 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    """Charm Event triggered when a TLS certificate is available."""
changed them to be more accurate. I don't want to specify that it's a CA certificate, since this relation could be used to send any type of certificate to be trusted.

2024-07-12 11:38 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    """Charm Event triggered when a TLS certificate is removed."""
updated, same comment as above

2024-07-12 11:40 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    """TLS certificates requirer class to be instantiated by TLS certificates requirers."""
true, changed.

2024-07-12 11:41 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +        """Generates/use private key and observes relation changed event.
changed.

2024-07-12 11:41 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +        """Emit certificate available event.
`Emits` is not in imperative mood. Added the `set` part

2024-07-12 11:44 UTC, kayra1 commented on tests/unit/charms/certificate_transfer_interface/v1/test_certificate_transfer_provides_v1.py
> +
this is how we've done it with @ghislainbourgeois in [tls-constraints-operator](https://github.com/canonical/tls-constraints-operator/blob/main/tests/unit/test_charm.py). I like it because I would consider specific mocked function calls to be implementation details and logs to be an expected output in a real deployment.

2024-07-12 15:55 UTC, ghislainbourgeois reviewed
This looks good, added some small comments, feel free to resolve them.

2024-07-12 15:55 UTC, ghislainbourgeois commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +        if len(relations) == 0:
```suggestion
        if not relations:
```

I think this would be more pythonic, but don't have strong feelings.

2024-07-12 15:55 UTC, ghislainbourgeois commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +        if len(relations) == 0:
```suggestion
        if not relations:
```

Same comment

2024-07-12 15:55 UTC, ghislainbourgeois commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    def _set_relation_data(self, relation: Relation, data: Set[str]) -> None:
```suggestion
from collections.abc import Iterable
[...]
    def _set_relation_data(self, relation: Relation, data: Iterable[str]) -> None:
```

This type hint would be a bit better, as we only need `data` to be iterable to pass it to `list()`.

2024-07-16 11:59 UTC, gruyaume requested changes

2024-07-16 11:59 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +ertificate-transfer interface.
```suggestion
certificate-transfer interface.
```

2024-07-16 11:59 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +juju relate <certificate_transfer provider charm> <certificate_transfer requirer charm>
```suggestion
juju integrate <certificate_transfer provider charm> <certificate_transfer requirer charm>
```

2024-07-16 11:59 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +You can relate both charms by running:
```suggestion
You can integrate both charms by running:
```

2024-07-16 11:59 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +PYDEPS = ["jsonschema"]
Why have this be a dependency? Where do we use json shemas?

2024-07-16 11:59 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +PYDEPS = ["jsonschema"]
We should likely use pydantic for data model validation. I've added this to the [tls interface library v4](https://github.com/canonical/tls-certificates-interface/pull/197), and you can also see examples of this in other charm interfaces (ex. ingress)

2024-07-16 11:59 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    def add_certificate(self, certificate: str, relation_id: Optional[int] = None) -> None:
Since what we insert in the relation data is a list, shouldn't we take a list of certs as an input and rename this to `add_certificates`?

2024-07-16 11:59 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +            certificate (str): Certificate
We may want to explicitly state the format we expect the cert to be in, and add input validation before inserting it into the relation data

2024-07-17 07:57 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +PYDEPS = ["jsonschema"]
gone

2024-07-19 10:28 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +PYDEPS = ["jsonschema"]
done

2024-07-22 07:15 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    def add_certificate(self, certificate: str, relation_id: Optional[int] = None) -> None:
I felt it would be easier for users to add certificates in a loop rather than have to create a list outside and set it at the end. I can change it though.

2024-07-22 07:18 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +            certificate (str): Certificate
done

2024-07-23 15:30 UTC, gruyaume requested changes

2024-07-23 15:30 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +            raise ValueError(msg) from e
I'm not convinced that this is the right error type. I'm not sure it's a better approach but in the tls lib v4 I went for a custom `DataValidationError`: 

```python
class TLSCertificatesError(Exception):
    """Base class for custom errors raised by this library."""


class DataValidationError(TLSCertificatesError):
    """Raised when data validation fails."""
```

2024-07-23 15:30 UTC, gruyaume commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    certificate_set_updated = EventSource(CertificateSetUpdatedEvent)
I'm not sure about the name of this event, I'd prefer `CertificatesAvailableEvent` which feels more symetric with `CertificatesRemovedEvent`

2024-07-23 15:30 UTC, gruyaume commented on test-requirements.in
> +jsonschema
Why do we need to add this requirement here?

2024-07-23 15:30 UTC, gruyaume commented on tests/unit/charms/certificate_transfer_interface/v1/test_certificate_transfer_requires_v1.py
No need to change this right away but this would be a good use case for scenario

2024-07-24 08:41 UTC, kayra1 commented on test-requirements.in
> +jsonschema
The unit tests for the v0 version of the library require it

2024-07-24 08:49 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +            raise ValueError(msg) from e
just copied these too

2024-07-24 08:54 UTC, kayra1 commented on lib/charms/certificate_transfer_interface/v1/certificate_transfer.py
> +    certificate_set_updated = EventSource(CertificateSetUpdatedEvent)
done

2024-07-24 11:42 UTC, gruyaume approved these changes

2024-07-24 12:26 UTC, kayra1 commented
TIL if you rebase when you have done a `commit suggestion`, the coauthor becomes unverified even if it was made on github

2024-07-24 14:29 UTC, merged