Add add_certificates function
canonical/certificate-transfer-interface pull request #96
Opened 2024-07-25 11:42 UTC by saltiyazan

# Description

When implementing this in the lego base lib I needed this function to have an efficient solution. 

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2024-07-25 11:50 UTC, kayra1 requested changes
please add at least 1 unit test for the new public function

2024-07-25 12:04 UTC, saltiyazan commented
> please add at least 1 unit test for the new public function. otherwise looks good.

At first I kept `add_certificate` as replacing it completely with `add_certificates` would be a breaking change.
But I'm certain the interface has not been used since merged (yesterday) I think this should be okay.
Fixed.

2024-07-26 09:02 UTC, kayra1 approved these changes

2024-07-26 09:04 UTC, kayra1 commented
> > please add at least 1 unit test for the new public function. otherwise looks good.
> 
> At first I kept `add_certificate` as replacing it completely with `add_certificates` would be a breaking change. But I'm certain the interface has not been used since merged (yesterday) I think this should be okay. Fixed.

I agree, it's also a comment I got from @gruyaume in the original PR. If this is more useful lets go with it.

2024-07-29 07:51 UTC, merged